behaviors:
  CarBrainSAC:
    trainer_type: sac
    hyperparameters:
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
      batch_size: 1024
      buffer_size: 50000
      buffer_init_steps: 0
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
      init_entcoef: 1.0
      save_replay_buffer: false
      tau: 0.005
      steps_per_update: 1
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 3
      # memory
      memory:
        sequence_length: 64
        memory_size: 256
    # Trainer configurations common to all trainers
    max_steps: 5.0e5
    time_horizon: 64
    summary_freq: 10000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: false
    init_path: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0


