behaviors:
  CarBrainSAC:
    trainer_type: sac
    hyperparameters:
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
      batch_size: 1024
      buffer_size: 10240
      buffer_init_steps: 1000
      init_entcoef: 1.0
      save_replay_buffer: false
      tau: 0.005
      steps_per_update: 1
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    time_horizon: 2048
    max_steps: 5.0e6
    summary_freq: 10000
    threaded: false

