behaviors:
  CarBrain:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 1
      epsilon: 2
      lambd: 3
      learning_rate: 4
      learning_rate_schedule: 5
      batch_size: 6
      buffer_size: 7
      beta: 8
    network_settings:
      normalize: true
      hidden_units: 9
      num_layers: 0
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    time_horizon: 128
    max_steps: 1.0e8
    summary_freq: 10000

