behaviors:
  CarBrain:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 5
      epsilon: 0.1
      lambd: 0.95
      learning_rate: 1e-4
      learning_rate_schedule: linear
      batch_size: 2048
      buffer_size: 20480
      beta: 1.0e-2
    network_settings:
      normalize: true
      hidden_units: 1024
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    time_horizon: 128
    max_steps: 1.0e8
    summary_freq: 10000

