behaviors:
  CarBrainPPO:
    trainer_type: ppo
    hyperparameters:
      num_epoch: 3
      epsilon: 0.1
      lambd: 0.95
      learning_rate: 1e-4
      learning_rate_schedule: linear
      batch_size: 1024
      buffer_size: 10240
      beta: 1.0e-2
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    time_horizon: 128
    max_steps: 1.0e8
    summary_freq: 10000
    threaded: false
  CarBrainSAC:
    trainer_type: sac
    hyperparameters:
      learning_rate: 1e-4
      learning_rate_schedule: linear
      batch_size: 512
      buffer_size: 5120
      buffer_init_steps: 1000
      init_entcoef: 1.0
      save_replay_buffer: false
      tau: 0.005
      steps_per_update: 1
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    time_horizon: 128
    max_steps: 1.0e8
    summary_freq: 10000
    threaded: false

